global class TestMergeAccConData {
    @AuraEnabled
    @InvocableVariable
    global String accountFirstName;
    
    @AuraEnabled
    @InvocableVariable
    global String accountLastName;
    
    @AuraEnabled
    @InvocableVariable
    global String contactFirstName;
    
    @AuraEnabled
    @InvocableVariable
    global String contactLastName;
    
    @AuraEnabled
    @InvocableVariable
    global String contactEmail;
}